spring:
  config:
    import: application_secret.yml
  datasource:
    url: jdbc:h2:file:./data/auth_db;MODE=MySql
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: NEVER
    schema: classpath:schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapper-locations:
    - /mappers/*.xml
user:
  profile:
    img:
      default: https://firebasestorage.googleapis.com/v0/b/userprofile-6905d.appspot.com/o/user%2Fdefault-user-icon.jpg?alt=media&token=f004f9ab-04f1-479e-a8b5-1ea975de0d7d
